### ISSUE TITLE
License information missing

### ISSUE THREAD

**Issue by ibressler** [Niels-Bohr-Institute-XNS-StructBiophys/BayesApp#2]
Hello everyone,
that is a great program and I wondered under which conditions it might be possible to include this program in other (open source) software packages for small-angle scattering analysis and under which conditions changes/contributions can be made?
Some licensing information would be very helpful for communicating those conditions. GitHub offers a guide and some templates for very common software licenses:
 https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

Thank you very much and best regards!

**Comment by andreashlarsen** [comment]
Hi Ingo, 

thank you. We will add a GPLv3 licence, so it can be used in other software packages. 

best regards, 
Andreas
